linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - exhaustruct
    - wsl
    - gofmt
    - goimports

run:
  timeout: 5m
  concurrency: 4
  issues-exit-code: 1
  tests: true

output:
  sort-results: true

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - tmp
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "Error return value of `.*(Close|Flush)` is not checked"
      linters:
        - errcheck
    - text: "shadow: declaration of"
      linters:
        - govet
    - text: "S1000: should use for range instead of for { select {} }"
      linters:
        - gosimple
