services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY} # This should be provided when running docker-compose
      - DATABASE_HOST=postgres # Override to use docker service name
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE_NAME=${DATABASE_DATABASE_NAME}
      - ETHEREUM_CHAIN_ID=314159
      - ETHEREUM_RPC=https://calibration.filfox.info/rpc/v1
      - ETHEREUM_STAKE_WALLET_ADDRESS=0x1fd2fA91C1eE96d128A35955EC3B496D7184c80A
      - ETHEREUM_TOKEN_ADDRESS=0xb3042734b608a1B16e9e86B374A3f3e389B4cDf0
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ENDPOINT=${SERVER_ENDPOINT}
      - SERVER_HOST=${SERVER_HOST}
      - FILECOIN_IPFS_ENDPOINT=${FILECOIN_IPFS_ENDPOINT}
      - FILECOIN_GATEWAY_URL=${FILECOIN_GATEWAY_URL}
      - FILECOIN_CREATE_STORAGE_DEALS=${FILECOIN_CREATE_STORAGE_DEALS}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
